const CLASS_NAME = "Mage";

// Mage-only bonus point support.
// Rune: "Rule-Bending Scroll" (id: "w6") grants +3 points.
// Bonus points do not count toward tier unlock requirements.
const TALENT_ENGINE_CONFIG = {
  baseMaxPoints: 51,
  bonusRune: {
    id: "w6",
    points: 3,
    runesStorageKey: "wow_runes_v1_mage",
    allocStorageKey: "wow_bonus_alloc_v1_mage"
  }
};

const talentData = {
    'arcane': {
        name: 'Temporal',
        talents: [
            { id: 'arcane-subtlety', name: 'Arcane Subtlety', maxPoints: 2, row: 0, col: 0, icon: 'spell_holy_dispelmagic.jpg', description: (p) => `Reduces your target's resistance to all of your spells by ${p * 5} and reduces the threat generated by your Arcane spells by ${p * 15}%.` },
            { id: 'arcane-focus', name: 'Arcane Focus', maxPoints: 5, row: 0, col: 1, icon: 'ability_evoker_rewind2.jpg', description: (p) => `Reduces the chance that the opponent can resist your Arcane spells by ${p * 2}%.` },
            { id: 'improved-arcane-missiles', name: 'Improved Arcane Missiles', maxPoints: 2, row: 1, col: 3, icon: 'spell_nature_starfall.jpg', description: (p) => `Gives you a ${p * 50}% chance to avoid interruption caused by damage while channeling Arcane Missiles and increases the number of missiles fired by ${p}.` },
	{ id: 'advanced-warding', name: 'Advanced Warding', maxPoints: 2, row: 0, col: 2, icon: 'ability_monk_forcesphere.jpg', description: (p) => `Increases the magnitude of your Mana Shield, Frost Ward, and Fire Ward by an amount equal to ${p * 100}% of your Spirit, and decreases mana drained by Mana Shield by ${p * 25}% per damage done.` },
            { id: 'regenerative-conduit', name: 'Regenerative Conduit', maxPoints: 5, row: 1, col: 1, icon: 'spell_mage_presenceofmind.jpg', description: (p) => `Your Wand hits deal ${p * 4}% additional damage and increase your total Spirit by ${p * 2}% for 15 sec.` },
	 { id: 'magic-absorption', name: 'Magic Absorption', maxPoints: 3, row: 2, col: 1, icon: 'spell_nature_astralrecalgroup.jpg', description: (p) => `Increases all resistances by ${p * 5} and causes all spells you fully resist or absorb to restore ${p * 2}% of your total mana.<hr>This effect can occur once every 12 sec.` },
 	{ id: 'bronze-flights-blessing', name: 'Bronze Flight\'s Blessing', maxPoints: 2, row: 5, col: 1, prereq: 'regenerate', icon: 'inv_misc_head_dragon_bronze.jpg', description: (p) => `The target of your Focus Magic always gains the effects of Temporal Beacon. In addition, increases the effect of your Amplify Magic and Dampen Magic spells by ${p * 25}%.` },
            { id: 'afterimage', name: 'Afterimage', maxPoints: 1, row: 1, col: 2, icon: 'achievement_guildperk_havegroup-willtravel.jpg', description: (p) => `Casting Blink causes a past version of yourself to appear, which casts spells on enemies for 15 sec. In addition, for each enemy you Blink through, the cooldown of Blink is reduced by 1 sec, up to 5 sec.` },
	{ id: 'spell-ward', name: 'Spell Ward', maxPoints: 5, row: 2, col: 2, icon: 'spell_priest_divinestar_shadow2.jpg', description: (p) => `Your Arcane Missiles spell has a ${p * 5}% chance to create a shield on a nearby ally, absorbing magic damage equal to ${p * 6}% of your damage dealt over the next 3 sec. Lasts 10 sec.` },
 	{ id: 'arcane-alacrity', name: 'Arcane Alacrity', maxPoints: 5, row: 5, col: 2, prereq: 'arcane-mind', icon: 'ability_argus_blightorb.jpg', description: (p) => `Arcane Blast increases the critical strike chance and damage of your next Arcane spell other than Arcane Blast by ${p * 2}%. Lasts 8 sec.` },
            { id: 'arcane-concentration', name: 'Arcane Concentration', maxPoints: 3, row: 1, col: 0, icon: 'spell_shadow_manaburn.jpg', description: (p) => `Gives you a ${p * 5}% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next spell by 100%.` },
	{ id: 'paradox', name: 'Paradox', maxPoints: 5, row: 3, col: 0, icon: 'spell_nzinsanity_desynchronized.jpg', description: (p) => `Your non-periodic damaging spells have a ${p * 2}% chance to create a Paradox around the target in a 10 yd radius, which slows all enemies by 40% and heals up to five allies within every sec. Lasts 5 sec.` },
            { id: 'time-dilation', name: 'Time Dilation', maxPoints: 3, row: 2, col: 3, icon: 'ability_evoker_stretchtime.jpg', description: (p) => `Allows ${p * 10}% of your Mana regeneration to continue while casting and reduces the damage you take from periodic spells and effects by ${p * 5}%.` },
	   { id: 'return-to-forever', name: 'Return to Forever', maxPoints: 1, row: 4, col: 0, prereq: 'regenerate', icon: 'ability_bossmagistrix_timewarp1.jpg', description: (p) => `Whenever you or an ally within 20 yds falls below 30% health, a future version of yourself appears to cast Regenerate on them. Your alternate self then casts spells on enemies for 15 sec before vanishing.
<hr>
This effect can occur once every 60 sec.` },
	{ id: 'glitch', name: 'Glitch', maxPoints: 3, row: 3, col: 1, icon: 'spell_arcane_arcane01_nightborne.jpg', description: (p) => { const values = [30, 20, 10]; return `Your Arcane Blast, Arcane Missles and Mystic Beam spells heal the lowest health party or raid member within 30 yds for an amount equal to ${p * 10}% of the damage done.`;}},
	{ id: 'regenerate', name: 'Regenerate', maxPoints: 1, row: 4, col: 1, icon: 'ability_evoker_rewind.jpg', details: ['40 yd range'], subDetails: ['19% of base mana','Instant'], description: (p) => `Heals the target over 3 sec and applies Temporal Beacon, causing 40% of all direct spell damage done by the caster to provide additional healing. Lasts 30 sec.` },
            { id: 'arcane-mind', name: 'Arcane Mind', maxPoints: 5, row: 3, col: 2, icon: 'inv_10_enchanting2_magicswirl_bronze.jpg', description: (p) => `Increases your maximum Mana by ${p * 2}%. In addition, while Hourglass Epiphany is on cooldown, your Return to Forever talent and all of your abilities cooldown ${p * 2}% faster.` },
            { id: 'magic-attunement', name: 'Magic Attunement', maxPoints: 3, row: 5, col: 0, icon: 'inv_inscription_80_vantusrune_uldir.jpg', description: (p) => `Reduces the cooldown of your Evocate by ${p * 60} sec and your Mana Shield, Frost Ward, and Fire Ward spells can now be cast on any friendly target.` },
		{ id: 'rewind-time', name: 'Rewind Time', maxPoints: 1, row: 5, col: 3, icon: 'spell_holy_borrowedtime.jpg', details: ['40 yd range','40 sec cooldown'], subDetails: ['18% of base mana','1 sec cast'], description: () => `Reverse a friendly target's injuries, instantly healing them for 30% of the damage they have taken over the last 6 sec. If the target returns to full Health during this time, the cooldown of this spell is reduced by 50%.` },
            { id: 'hourglass-epiphany', name: 'Hourglass Epiphany', maxPoints: 1, row: 6, col: 1, isUltimate: true, icon: 'ability_evoker_timedilation.jpg', details: ['3 min cooldown'], subDetails: ['20% of base mana','Instant'], description: () => `Instantly refreshes the duration of any active Temporal Beacons and increases your spell damage and healing by 30%. Lasts 15 sec.
<hr>
While this effect is active, the global cooldown of your Blink, Mana Shield and Ward spells is reduced by 100%.` },
        ]
    },
    'fire': {
        name: 'Occult',
        talents: [
              { id: 'mystic-beam', name: 'Mystic Beam', maxPoints: 1, row: 0, col: 0, prereq: 'forgotten-knowledge', icon: 'inv_112_arcane_beam.jpg', details: ['30 yd range','6 sec cooldown'], subDetails: ['10% of base mana','Channeled (2 sec cast)'], description: () => `Channel a magic beam onto the target for 2 sec, dealing Arcane damage every 0.50 sec.` },
{ id: 'forgotten-knowledge', name: 'Forgotten Knowledge', maxPoints: 5, row: 0, col: 1, icon: 'inv_10_enchanting_enchantingoils_color2.jpg', description: (p) => `Increases the critical strike damage bonus of your Arcane spells by ${p * 20}%.` },
	{ id: 'animate-wand', name: 'Animate Wand', maxPoints: 3, row: 4, col: 0, icon: 'inv_enchanting_70_toy_leyshocker.jpg', description: (p) => `Your non-periodic spell hits have a ${p * 5}% chance to cause your equipped wand to come to life for 10 seconds, autonomously assisting you in combat and shooting your target for ${p * 50}% of ranged weapon damage.<hr>During this time you cannot shoot your wand.` },
            { id: 'adaptive-arcana', name: 'Adaptive Arcana', maxPoints: 5, row: 0, col: 2, icon: 'inv_ability_mage_shiftingpower.jpg', description: (p) => `Your Arcane spells channel ${p * 2}% faster.<br><br>Your Fire spells generate ${p * 2}% less threat.<br><br>Your Frost spells cost ${p * 2}% less mana.` },
	{ id: 'incanters-ward', name: 'Incanter\'s Ward', maxPoints: 1, row: 1, col: 1, prereq: 'forgotten-knowledge', icon: 'inv_soulbarrier.jpg', description: () => `Your Mana Shield can now absorb magic damage and knocks all enemies within 6 yards backwards 10 yards when destroyed.` },
            { id: 'spellflux', name: 'Spellflux', maxPoints: 2, row: 5, col: 0, icon: 'spell_mage_nethertempest.jpg', description: (p) => `After landing 3 non-periodic Arcane spell critical strikes, your target becomes unstable, accumulating ${p * 10}% of the damage you deal to them for 10 sec. The target then unleashes that amount as Arcane damage on up to 3 nearby enemies.` },
	{ id: 'presence-of-mind', name: 'Presence of Mind', maxPoints: 1, row: 2, col: 2, icon: 'spell_nature_enchantarmor.jpg', details: ['5 min cooldown'], subDetails: ['Instant'], description: (p) => `When activated, your next Mage spell with a casting time less than 10 sec becomes instant cast.` },
            { id: 'spelltwisting', name: 'Spelltwisting', maxPoints: 5, row: 3, col: 1, icon: 'inv_misc_profession_book_jewelcrafting.jpg', description: (p) => `Your Mystic Beam spell has a ${p * 8}% chance to cause your next Arcane Missles spell to fire an additional missile at the end of its duration that deals 50% of the spell's total damage.` },
	{ id: 'enlightened-magus', name: 'Enlightened Magus', maxPoints: 2, row: 3, col: 2, icon: 'ability_mage_greaterinvisibility.jpg', description: (p) => `Increases your total Intellect by ${p * 5}%.<br><br>Whenever you take or absorb spell damage your resistance for that type increases by ${p * 10}% for 10 sec.<hr>This effect can occur once every 20 sec.` },
	{ id: 'spellwhisperer', name: 'Spellwhisperer', maxPoints: 5, row: 2, col: 1, icon: 'spell_mage_evanesce.jpg', description: (p) => `Your Arcane Blast has a ${p * 6}% chance to reduce the channeled duration and mana cost of your next Arcane Missiles by 50%, and cause missiles to fire every 0.5 sec.` },
	{ id: 'overwhelming-power', name: 'Overwhelming Power', maxPoints: 2, row: 3, col: 3, icon: 'spell_misc_zandalari_council_soulswap.jpg', description: (p) => `Your Mystic Beam spell no longer costs mana and increases the damage of your Arcane Explosion by ${p * 20}% but decreases your Spirit by 20%. Stacks up to 5 times. Lasts 30 sec. If your Spirit reaches 0, you die.` },
	{ id: 'usurp-essence', name: 'Usurp Essence', maxPoints: 3, row: 4, col: 3, icon: 'spell_arcane_manatap.jpg', description: (p) => `Whenever the target of your Focus Magic lands a spell critical strike, you are drained of ${p * 1}% of your total Health, but your next spell gains ${p * 1}% increased chance to critically strike. Lasts 6 sec.` },
            { id: 'balefire-beam', name: 'Balefire Beam', maxPoints: 3, row: 5, col: 3, icon: 'spell_fire_twilightflamebolt.jpg', description: (p) => `Your Mystic Beam spell cycles through every magic type, from Arcane to Holy to Frost to Shadow to Fire to Nature. Each time you complete a full cycle, your spell damage is increased by ${p * 5}% for 15 sec.` },
	  { id: 'focused-mind', name: 'Focused Mind', maxPoints: 2, row: 1, col: 2, icon: 'ability_kaztik_dominatemind.jpg', description: (p) => `Reduces the pushback suffered from damaging attacks while casting spells by ${p * 30}% and reduces the duration of interrupt effects on you by ${p * 10}%.` },
 	{ id: 'brilliant-arrogance', name: 'Brilliant Arrogance', maxPoints: 5, row: 1, col: 0, icon: 'ability_mage_potentspirit.jpg', description: (p) => `Increases your chance to critically strike with spells by ${p * 1}%, but increases damage taken from spells by ${p * 1}%.` },
{ id: 'spell-morph', name: 'Mirrorspell', maxPoints: 1, row: 6, col: 1,  isUltimate: true, icon: 'ability_socererking_arcanemines.jpg', description: (p) => `Your <span class="text-white">Counterspell</span> spell transforms into:`, subSpell: { name: 'Mirrorspell',

    // Optional: small icon next to the subspell name
    icon: 'ability_socererking_arcanemines.jpg',

    // Left column (white text, stacked)
    left: ['28% of base mana','Instant'],

    // Right column (white text, stacked)
    right: ['30 yd range','15 sec cooldown'],

    // Body text (yellow like normal descriptions)
    body: `Places a ward on a friendly target that persists for 10 sec, triggering when they next spend mana on a spell. Once triggered, allows the Mage to unleash a similar version of that spell.<hr>If the copied spell has a cooldown greater than 15 sec, this spell's cooldown increases to match it.`,
  }
},
	{ id: 'pandora', name: 'Pandora', maxPoints: 3, row: 5, col: 2, icon: 'spell_argus_psychic_scarring.jpg', description: (p) => `Your Evocation spell lasts ${p * 1} sec longer and siphons all enemies within 10 yds, removing one beneficial magic effect from each every sec.` },
            { id: 'mystic-power', name: 'Mystic Power', maxPoints: 5, row: 4, col: 1, icon: 'spell_mage_overpowered.jpg', description: (p) => `Increases your spell haste by ${p * 1}% and the damage of your Arcane Missiles spell by an amount equal to ${p * 4}% of your spell power.` },
	{ id: 'disintegrate', name: 'Disintegrate', maxPoints: 1, row: 2, col: 0, prereq: 'spellwhisperer', icon: 'ability_mage_arcanesurge.jpg', details: ['35 yd range','2 min cooldown'], subDetails: ['100% of total mana','Instant'], description: (p) => `Unleash a surge of energy at the target dealing Arcane damage. Damage is increased by up to 300% based on the amount of mana consumed.
<hr>
Afterward, your mana regeneration is activated and increased by 300% for 8 sec.` },
            { id: 'forbidden-magic', name: 'Forbidden Magic', maxPoints: 1, row: 5, col: 1, icon: 'inv_7xp_inscription_talenttome02.jpg', description: (p) => `All talents, consumables and effects that benefit or modify your Arcane damage now apply to every school of magic.` },
	{ id: 'knowledge-unbound', name: 'Knowledge Unbound', maxPoints: 1, row: 4, col: 2, icon: 'ability_mage_incantersabsorbtion.jpg', description: (p) => `Your spell critical strikes grant Profane Knowledge while in combat, causing your damaging spells to treat enemies as if you were 3 levels higher. Lasts 10 sec.
<hr>
Landing a killing blow on an enemy that yields experience or honor immediately grants you this effect.` },
        ]
    },
    'frost': {
        name: 'Elemental',
        talents: [
            { id: 'rapid-spellcasting', name: 'Rapid Spellcasting', maxPoints: 5, row: 0, col: 1, icon: 'spell_mage_thermalvoid.jpg', description: (p) => `Reduces the cast time of your Frostbolt, Fireball, and Arcane Blast by ${p * 2}%.` },
            { id: 'elemental-precision', name: 'Elemental Precision', maxPoints: 3, row: 0, col: 2, icon: 'inv_shadowflame_missile.jpg', description: (p) => `Reduces the chance that the opponent can resist your Frost and Fire spells by ${p * 1}%.` },
		{ id: 'thermal-fluctuation', name: 'Thermal Fluctuation', maxPoints: 5, row: 1, col: 0, icon: 'spell_frostresistancetotem_01.jpg', description: (p) => `Increases the critical strike damage bonus of your Frost spells by ${p * 20}% and increases the critical strike chance of your Fire spells by ${p * 2}%. This effect is doubled versus Elemental and Mechanical creatures.` },
            { id: 'permafrost', name: 'Permafrost', maxPoints: 3, row: 1, col: 2, icon: 'spell_frost_wisp.jpg', description: (p) => `Increases the duration of your Chill effects by ${p} sec and gives your Chill effects a ${p * 5}% chance to freeze the target for 3 sec.` },
            { id: 'icy-inferno', name: 'Icy Inferno', maxPoints: 2, row: 2, col: 3, icon: 'inv_shadowflame_groundstate.jpg', description: (p) => `Your Cone of Cold and Frost Nova spells have a ${p * 50}% chance to make your next Flamestrike instant cast and cost ${p * 50}% less mana.` },
           { id: 'hot-and-cold', name: 'Hot and Cold', maxPoints: 1, row: 1, col: 1, icon: 'inv_everburningignition_blue.jpg', description: (p) => `Your Frost spells increase the damage of your Fire spells by 2% for 1 min. Your Fire spells increase the damage of your Frost spells by 2% for 1 min. Each effect stacks up to 5 times.` },
            { id: 'flamefrost-adapation', name: 'Flamefrost Adaptation', maxPoints: 2, row: 2, col: 1, icon: 'spell_azerite_essence06.jpg', description: (p) => `Casting Frostbolt transforms your next Fire Blast into Frost Blast, dealing ${p * 25}% increased damage against Chilled and Frozen targets.` },
            { id: 'dead-of-winter', name: 'Dead of Winter', maxPoints: 2, row: 4, col: 0, icon: 'ability_deathknight_remorselesswinters2.jpg', description: (p) => `Your Iceblock spell creates a Blizzard above you while active. In addition, Blizzard gains a Chill effect, lowering the target's movement speed by ${p * 20}%. Lasts 2 sec.` },
	{ id: 'elemental-reach', name: 'Elemental Reach', maxPoints: 2, row: 3, col: 0, icon: 'spell_azerite_essence07.jpg', description: (p) => `Increases the range of your Fireball, Fire Blast, Frost Blast and Frostbolt by ${p * 3} yards. In addition, the radius of your Flamestrike and Cone of Cold is increased by ${p * 10}%.` },
            { id: 'elemental-efficiency', name: 'Elemental Efficiency', maxPoints: 2, row: 3, col: 1, icon: 'spell_fire_masterofelements.jpg', description: (p) => `Your Fire and Frost spell criticals refund ${p * 10}% of their base mana cost.` },
	{ id: 'frostfire-lance', name: 'Frostfire Lance', maxPoints: 1, row: 3, col: 2, icon: 'inv_ability_frostfiremage_frostfirebolt.jpg', details: ['35 yd range','10 sec cooldown'], subDetails: ['18% of base mana','0.5 sec cast'], description: () => `Deals Frostfire damage and causes additional damage over 6 sec. Checks the lower of the target's Frost and Fire resists and counts as both types of damage.` },
	{ id: 'fiery-payback', name: 'Fiery Payback', maxPoints: 1, row: 2, col: 2, prereq: 'icy-inferno', icon: 'spell_burningbladeshaman_blazing_radiance.jpg', description: (p) => `Falling below 30% health causes you to unleash a nova, dealing Fire damage to all enemies within 15 yds. Every enemy hit reduces the cooldown of Ice Block by 5%.<hr>This effect can occur once every 2 min.` },
            { id: 'master-of-elements', name: 'Master of Elements', maxPoints: 2, row: 4, col: 2, icon: 'ability_monk_counteractmagic.jpg', description: (p) => `Your Fire Blast and Frost Blast critical strikes reduce the cooldown of Convergence by ${p * 2} sec and reduce the cast time of your next Fireball or Frostbolt by ${p * 15}%.` },
            { id: 'convergence', name: 'Convergence', maxPoints: 1, row: 4, col: 1, icon: 'inv12_ability_mage_isothermiccore.jpg', details: ['3 min cooldown'], subDetails: ['5% of base mana','Instant'], description: () => `When activated, your Fire and Frost spells deal 20% increased damage. Each non-critical strike increases the critical strike chance with spells of the opposite school by 5%. Lasts 20 sec.` },
	{ id: 'vitrification', name: 'Vitrification', maxPoints: 5, row: 5, col: 2, icon: 'ability_mage_tormentoftheweak.jpg', description: (p) => `The periodic damage of your Fireball spell is now also a Chill effect. In addition, applying a Chill or burning effect to an enemy increases their Fire and Frost damage taken by 1%. Stacks up to 5 times. Lasts  ${p * 6} sec.` },
	{ id: 'scorching-cold', name: 'Scorching Cold', maxPoints: 1, row: 5, col: 3, prereq: 'vitrification', icon: 'ability_siege_engineer_purification_beam.jpg', description: (p) => `Scorch can be cast while moving and restores 5% of your missing Mana when striking targets that are both Chilled and burning.` },
            { id: 'chillbrand-ignition', name: 'Chillbrand Ignition', maxPoints: 5, row: 3, col: 3, icon: 'spell_fire_blueimmolation.jpg', description: (p) => `Your critical strikes from non-periodic Fire and Frost damage spells cause the target to burn for an additional ${p * 6}% of the spell's damage over 4 sec.` },
	{ id: 'heat-death', name: 'Heat Death', maxPoints: 2, row: 5, col: 0, icon: 'ability_mage_coldasice.jpg', description: (p) => `Landing 2 non-periodic spell criticals in a row with Fireball, Frostbolt, or Frostfire Lance causes your next Cryoburn within 6 sec to be instant cast and cost ${p * 40}% less mana.` },
	{ id: 'cryoburn', name: 'Cryoburn', maxPoints: 1, row: 6, col: 1, isUltimate: true, prereq: 'convergence', icon: 'spell_frostfire-orb.jpg', details: ['35 yd range'], subDetails: ['22% base mana','5 sec cast'], description: () => `Blasts the target with coldflame magic that causes initial Frost damage and additional Fire damage over 12 sec.
<hr>
This ability counts as a Fire and Frost spell.` },
        ]
    }
};
