const CLASS_NAME = "Paladin";

const talentData = {
    'holy': {
        name: 'Holy',
        talents: [
            { id: 'divine-power', name: 'Divine Power', maxPoints: 5, row: 0, col: 1, icon: 'inv_ability_skyriding_glyph.jpg', description: (p) => `Increases your total Strength and Intellect by ${p * 1}%.` },
            { id: 'purifying-power', name: 'Purifying Power', maxPoints: 3, row: 1, col: 3, icon: 'spell_holy_purifyingpower.jpg', description: (p) => `Cleansing or Purifying a friendly target increases your casting speed and attack speed by 10% for ${p * 3} sec.`},
	{ id: 'wrathful-light', name: 'Wrathful Light', maxPoints: 2, row: 1, col: 0, icon: 'spell_nature_wrathv2.jpg', description: (p) => `Reduces the cooldown of your Holy Wrath spell by ${p * 25}% and increases its damage by ${p * 10}%.` },
            { id: 'spiritual-teachings', name: 'Spiritual Teachings', maxPoints: 2, row: 4, col: 0, icon: 'spell_paladin_divinecircle.jpg', description: (p) => `Your Flash of Light and Holy Light spells have a ${p * 25}% chance to not lose casting time when you take damage. In addition, the cooldown of your Lay on Hands spell is reduced by ${p * 10} mins.` },
            { id: 'seals-of-the-pure', name: 'Seals of the Pure', maxPoints: 3, row: 0, col: 2, icon: 'ability_thunderbolt.jpg', description: (p) => `Increases the damage done by your Seal of Righteousness, Seal of Command, Seal of Martyrdom and their Judgement effects by ${p * 5}%.` },
		{ id: 'blessed-path', name: 'Blessed Path', maxPoints: 5, row: 1, col: 1, icon: 'spell_holy_unyieldingfaith.jpg', description: (p) => `Your Consecration spell heals party members within the area for an amount equal to ${p * 2}% of your bonus healing and reduces physical damage dealt by enemies within the area by 3%.` },
            { id: 'soothing-light', name: 'Soothing Light', maxPoints: 5, row: 2, col: 1, icon: 'spell_holy_holybolt.jpg',  description: (p) => `Reduces the threat generated by your Holy spells and effects by ${p * 3}%. In addition, your Flash of Light and Holy Light critical heals have a ${p * 20}% chance to refund their base mana cost.` },
             { id: 'illumination', name: 'Illumination', maxPoints: 5, row: 3, col: 2, icon: 'paladin_holy.jpg', description: (p) => `While Seal of Light is active, the damage done by your Divine Verdict and Exorcism spells is increased by ${p * 2}%.
<br>
<br>
While Seal of Wisdom is active, the healing done by your Holy Shock and Glory spells is increased by ${p * 2}%.` },
            { id: 'apostle', name: 'Apostle', maxPoints: 5, row: 2, col: 2, icon: 'spell_paladin_clarityofpurpose.jpg', description: (p) => `Gives you a ${p * 1}% bonus to damage and healing for 15 sec after causing a critical effect from Holy Shock, Flash of Light or Holy Light.` },
	{ id: 'aura-mastery', name: 'Aura Mastery', maxPoints: 1, row: 4, col: 2, prereq: 'divine-favor', icon: 'spell_holy_auramastery.jpg', description: (p) => `Your active Aura increases Holy damage dealt by 10% and reduces the duration of any Silence or Interrupt effect used against party members by 20%.` },
		{ id: 'glory', name: 'Glory', maxPoints: 1, row: 3, col: 1, icon: 'achievment_raid_houroftwilight.jpg', details: ['20 yd range','30 sec cooldown'], subDetails: ['20% of base mana', 'Instant'], description: (p) => `Unleash a wave of light that heals up to 5 of the most injured party or raid members and damages up to 5 enemies in a 20 yard frontal cone. Enemies facing you are disoriented for up to 3 sec. ` },
            { id: 'divine-favor', name: 'Divine Favor', maxPoints: 1, row: 4, col: 1, icon: 'ability_paladin_infusionoflight.jpg', details: ['2 min cooldown'], subDetails: ['3% of base mana','Instant'], description: () => `Gives your next Holy spell a 100% critical effect chance.` },
            { id: 'virtue', name: 'Virtue', maxPoints: 1, row: 2, col: 0, prereq: 'soothing-light',  icon: 'ability_paladin_beaconsoflight.jpg', description: (p) => `Casting a direct heal on any target except yourself grants you Virtue, healing you for 20% of the healing done over 6 sec.` },
	{ id: 'enduring-hope', name: 'Enduring Hope', maxPoints: 2, row: 1, col: 2, icon: 'spell_holy_healingaura.jpg', description: (p) => `Reduces the duration of all Stun and Fear effects on you  by ${p * 10}% and reduces the chance your helpful spells and damage over time effects will be dispelled by an additional ${p * 10}%.` },
	{ id: 'providence', name: 'Providence', maxPoints: 2, row: 5, col: 0, icon: 'spell_holy_lightsgrace.jpg', description: (p) => { const values = [15, 30]; return `Whenever you heal a target at or below 30% health, your next Holy Wrath or Holy Light has a ${values[p - 1]}% reduced cast time. Lasts 10 sec.`;}},
            { id: 'perdition', name: 'Perdition', maxPoints: 2, row: 4, col: 3, icon: 'spell_holy_power.jpg', description: (p) => `Your Exorcism and Holy Shock spells cause the target to become vulnerable, increasing the damage they take from your Holy spells and effects by 1%. Stacks up to ${p * 5} times. Lasts 1 min.` },
	{ id: 'sacred-shield', name: 'Sacred Shield', maxPoints: 5, row: 5, col: 3, icon: 'ability_paladin_blessedmending.jpg', description: (p) => `Whenever you critically heal with Flash of Light the target gains an absorption shield equal to ${p * 3}% of your bonus healing effects and has a ${p * 6}% increased chance to be critically healed by your Flash of Light for 8 sec.<hr>This effect can occur once every 30 sec.` },
	{ id: 'lights-messenger', name: 'Light\'s Messenger', maxPoints: 5, row: 5, col: 2, icon: 'ability_paladin_artofwar.jpg', description: (p) => `Each spear cast by Divine Verdict has a ${p * 2}% chance to reset the cooldown of Holy Shock.<br><br>Your Holy Shock and Holy Wrath sear targets struck for ${p * 6}% additional Holy damage over 6 sec.` },
	{ id: 'divine-verdict', name: 'Divine Verdict', maxPoints: 1, row: 5, col: 1, prereq: 'divine-favor', icon: 'spell_paladin_inquisition.jpg', details: ['40 yd range','12 sec cooldown'], subDetails: ['17% of base mana','Instant'], description: () => `Summon a spear of light above you every 2 seconds for 6 sec. Afterwards, the 3 spears hurtle to your target one by one, causing Holy damage to an enemy or healing an ally.` },
            { id: 'holy-shock', name: 'Holy Shock', maxPoints: 1, row: 6, col: 1, icon: 'spell_holy_searinglight.jpg', details: ['20 yd range','20 sec cooldown'], subDetails: ['15% of base mana','Instant'], description: () => `Blasts the target with Holy energy, causing Holy damage to an enemy, or healing an ally.` },
        ]
    },
    'protection': {
        name: 'Protection',
        talents: [
            { id: 'benediction', name: 'Benediction', maxPoints: 2, row: 0, col: 1, icon: 'spell_frost_windwalkon.jpg', description: (p) => `Reduces the Mana cost of your Judgement and Seal spells by ${p * 15}%.` },
            { id: 'redoubt', name: 'Redoubt', maxPoints: 5, row: 0, col: 2, icon: 'inv_shield_1h_bastionquest_b_01.jpg', description: (p) => `Increases your chance to block attacks with a shield by ${p * 4}% after being hit by a melee or ranged attack. Lasts 10 sec or 5 blocks.` },
	{ id: 'spiritual-attunement', name: 'Spiritual Attunement', maxPoints: 2, row: 3, col: 3, icon: 'spell_holy_revivechampion.jpg', description: (p) => `Gives the Paladin mana when healed by other friendly targets. The amount of mana gained is equal to ${p * 5}% of the amount healed.
<hr>
Mana gained from overhealing is reduced by 90%.` },
            { id: 'honed-light', name: 'Honed Light', maxPoints: 3, row: 0, col: 0, icon: 'inv_10_blacksmithing_consumable_sharpeningstone_color2.jpg', description: (p) => `Increases your chance to hit with Holy spells and weapon attacks by ${p * 1}%. This effect is doubled when fighting Undead and Demons.` },
	{ id: 'devout-defender', name: 'Devout Defender', maxPoints: 5, row: 1, col: 0, icon: 'ability_paladin_judgementofthepure.jpg', description: (p) => `Increases your Parry chance by ${p * 1}%. In addition, each successful Parry reduces the cast time of your next Flash of Light spell by ${p * 15}%. Stacks up to 5 times.` },
            { id: 'guardians-favor', name: 'Guardian\'s Favor', maxPoints: 2, row: 1, col: 1, icon: 'spell_holy_sealofprotection.jpg', description: (p) => `Reduces the cooldown of your Blessing of Protection by ${p * 60} sec and increases the duration of your Blessing of Freedom by ${p * 2} sec.` },
            { id: 'toughness', name: 'Toughness', maxPoints: 5, row: 2, col: 1, icon: 'spell_holy_devotion.jpg', description: (p) => `Increases your armor value from items by ${p * 2}% and increases your Defense skill by ${p * 2}.` },
            { id: 'denounce', name: 'Denounce', maxPoints: 1, row: 3, col: 1, icon: 'misc_legionfall_paladin.jpg', details: ['15 yd range','30 sec cooldown'], subDetails: ['16% of base mana', 'Instant'], description: () => `Sear the target with light, causing Holy damage and preventing their melee and ranged attacks from critically striking the Paladin for the next 10 sec.` },
            { id: 'righteous-guard', name: 'Righteous Guard', maxPoints: 1, row: 2, col: 0, prereq: 'devout-defender', icon: 'ability_paladin_speedoflight.jpg', description: (p) => { const values = [25, 50]; return `While Righteous Fury is active, causes you to heal for 10% of all Holy damage done and allows you to Parry while casting spells.`;}},
            { id: 'shield-specialization', name: 'Shield Specialization', maxPoints: 3, row: 2, col: 2, prereq: 'redoubt', icon: 'inv_shield_1h_silverhand_b_02.jpg', description: (p) => `Increases the amount of damage absorbed by your shield by ${p * 10}% and causes your blocks to restore ${p * 5}% of your missing mana.` },
		{ id: 'holy-shield', name: 'Holy Shield', maxPoints: 1, row: 2, col: 3, prereq: 'shield-specialization', icon: 'spell_holy_blessingofprotection.jpg', details: ['10 sec cooldown'], subDetails: ['4% of base mana','Instant'], description: (p) => `Increases block chance by 30% and deals Holy damage for each attack blocked. Lasts 10 sec.
<hr>
Recasting this ability consumes Holy Shield's effect and causes the Paladin to strike the target with Righteous Shield, causing Holy damage.` },
            { id: 'improved-lay-on-hands', name: 'Improved Lay on Hands', maxPoints: 1, row: 1, col: 3, icon: 'spell_holy_layonhands.jpg', description: (p) => `Your Lay on Hands spell now has unlimited range and gives the target a ${p * 20}% bonus to their armor value from items for 2 min.` },
	{ id: 'adjudication', name: 'Adjudication', maxPoints: 5, row: 3, col: 2, icon: 'ability_paladin_intercession.jpg', description: (p) => `Increases the critical strike chance of Avenger's Shield and Exorcism by ${p * 3}% and the damage done by Denounce and Righteous Shield by ${p * 4}%.` },
	{ id: 'worthy', name: 'Worthy', maxPoints: 5, row: 4, col: 0, icon: 'ability_paladin_judgementsofthejust.jpg', description: (p) => `Your Holy Shield, Flash of Light and Judgement spells increase your total Stamina, Intellect and Strength by 1%. Stacks up to 5 times. Lasts ${p * 6} sec.` },
            { id: 'sanctuary', name: 'Sanctuary', maxPoints: 1, row: 4, col: 1, icon: 'ability_paladin_savedbythelight.jpg', description: () => `Reduces all spell damage taken by party members within 20 yds by 3%.<br><br>Whenever a party or raid member falls below 40% total Health, the cooldown of your Hand of Reckoning is reset and your next Holy Light becomes instant.
<hr>
This effect can occur once every 90 sec.` },
            { id: 'reckoning', name: 'Reckoning', maxPoints: 2, row: 4, col: 2, icon: 'spell_holy_blessingofstrength.jpg', description: (p) => `Gives you a ${p * 5}% after blocking, parrying or being hit by any damaging attack for your next 3 weapon swings within 8 sec to generate an additional attack.` },
	{ id: 'last-light', name: 'Last Light', maxPoints: 1, row: 5, col: 3, icon: 'ability_paladin_longarmofthelaw.jpg', description: (p) => `Damage that would otherwise kill you causes you to gain an absorption shield equal to 100% of your maximum Health for 10 sec.<br><br>When this effect expires or is removed by any means, you emit a nova of light that heals all party and raid members within 30 yds.<hr>This effect can occur once every 5 min.` },
		{ id: 'celestial-aid', name: 'Celestial Aid', maxPoints: 1, row: 5, col: 0, icon: 'ability_paladin_holyavenger.jpg', details: ['3 min cooldown'], subDetails: ['30% of base mana', 'Instant'], description: (p) => `Calls forth a Holy Guardian from the heavens to assist you in combat. Lasts 30 sec.` },
            { id: 'light-infused-armament', name: 'Light-Infused Armament', maxPoints: 5, row: 5, col: 2, icon: 'ability_paladin_blindinglight.jpg', description: (p) => `Your equipped main-hand weapon glows with light, restoring ${p * 1}% of your total Mana and dealing additional Holy damage whenever you strike an enemy.` },
            { id: 'avengers-shield', name: 'Avenger\'s Shield', maxPoints: 1, row: 6, col: 1, isUltimate: true, prereq: 'sanctuary', icon: 'spell_holy_avengersshield.jpg',  details: ['30 yd range','20 sec cooldown'], subDetails: ['12% of base mana','1 sec cast'], description: (p) => `Hurls a holy shield at the enemy, dealing Holy damage, dazing them and then jumping to additional nearby enemies. Affects 3 total targets. Lasts 5 sec.` },
        ]
    },
    'retribution': {
        name: 'Retribution',
        talents: [
            { id: 'inquisition', name: 'Inquisition', maxPoints: 5, row: 0, col: 1, icon: 'spell_holy_crusade.jpg', description: (p) => `Increases your damage done with Holy spells and effects by  ${p * 1}%. In addition, when an enemy you have damaged within the last 5 sec dies, the first healing spell you cast on yourself costs ${p * 20}% less mana.
<hr>
This effect only triggers from enemies that yield experience or honor.` },
	{ id: 'eye-for-an-eye', name: 'Eye for an Eye', maxPoints: 5, row: 1, col: 2, icon: 'spell_holy_eyeforaneye.jpg', description: (p) => `Your Retribution Aura deals ${p * 20}% increased damage and triggers onto enemies that strike you with a direct damage spell.` },
            { id: 'swift-judgments', name: 'Swift Judgements', maxPoints: 2, row: 1, col: 0, icon: 'spell_holy_righteousfury.jpg', description: (p) => `Decreases the cooldown of your Judgement spell by ${p * 1} sec and increases its range by 5 yards.` },
            { id: 'heart-of-the-crusader', name: 'Heart of the Crusader', maxPoints: 3, row: 0, col: 2, icon: 'spell_holy_holysmite.jpg', description: (p) => `Your Judgement spell increases the critical strike chance of all attacks made against the target by an additional ${p * 1}%.` },
            { id: 'vindicator', name: 'Vindicator', maxPoints: 2, row: 3, col: 0, icon: 'spell_holy_vindication.jpg', description: (p) => `Whenever a party or raid member within ${p * 10} yds is the victim of a critical strike or damage that exceeds 20% of their total Health, your next 2 melee attacks deal 15% increased damage. Lasts 10 sec.` },
            { id: 'conviction', name: 'Conviction', maxPoints: 5, row: 1, col: 1, icon: 'spell_holy_retributionaura.jpg', description: (p) => `Increases your chance to get a critical strike with all spells and attacks by ${p * 1}%. This effect is doubled when fighting Undead and Demons.` },
	{ id: 'scorn-the-cowardly', name: 'Scorn the Cowardly', maxPoints: 1, row: 2, col: 2, prereq: 'eye-for-an-eye', icon: 'ability_paladin_turnevil.jpg', description: (p) => `Your melee attacks can now trigger Retribution Aura on enemies that are not facing you. ` },
            { id: 'seal-of-command', name: 'Seal of Command', maxPoints: 1, row: 2, col: 3, icon: 'ability_warrior_innerrage.jpg', subDetails: ['3% of base mana', 'Instant'], description: () => `
Gives the Paladin a chance to deal additional Holy damage equal to 80% of normal weapon damage. Only one Seal can be active on the Paladin at any one time. Lasts 30 sec.
<hr>
Unleashing this Seal's energy will judge an enemy, instantly causing Holy damage, increased by 100% if the target is stunned, immobilized, Undead or Demon.` },
            { id: 'pursuit-of-justice', name: 'Pursuit of Justice', maxPoints: 2, row: 3, col: 2, icon: 'spell_holy_persuitofjustice.jpg', description: (p) => `Your Judgement spell increases your movement speed by ${p * 5}% for 3 sec.
<br>
<br>
While mounted, your movement speed increases by ${p * 1}% every sec. Stacks up to 5 times.` },
	{ id: 'faithful-executor', name: 'Faithful Executor', maxPoints: 2, row: 3, col: 3, icon: 'spell_paladin_executionsentence.jpg', description: (p) => `Hammer of Wrath is castable while moving and heals up to 3 party members for ${p * 15}% of the damage caused. ` },
            { id: 'sheath-of-light', name: 'Sheath of Light', maxPoints: 3, row: 4, col: 1, icon: 'ability_paladin_sheathoflight.jpg', description: (p) => `Dealing damage with your melee weapon increases your spell damage by an amount equal to ${p * 10}% of your Attack Power for 15 sec.` },
            { id: 'veneration', name: 'Veneration', maxPoints: 1, row: 5, col: 0, icon: 'ability_paladin_veneration.jpg', description: (p) => `Transforms your <span class="text-white">Blessing of Sacrifice</span> spell into:`, subSpell: { name: 'Veneration',

    // Optional: small icon next to the subspell name
    icon: 'ability_paladin_veneration.jpg',

    // Left column (white text, stacked)
    left: ['3% of base mana','Instant'],

    // Right column (white text, stacked)
    right: ['30 yd range','30 sec cooldown'],

    // Body text (yellow like normal descriptions)
    body: `Pray over a friendly target, causing 3% of the damage they take to be redirected to you and causing spells you cast on them to refund their base mana cost. Lasts 30 min.<hr>This effect can only be on one target at a time.`,
  }
},
            { id: 'divine-potency', name: 'Divine Potency', maxPoints: 3, row: 2, col: 0, icon: 'ability_paladin_swiftretribution.jpg', description: (p) => `Your Auras also increase casting, ranged and melee attack speed by ${p * 1}%. This effect is increased by an additional by 2% on the Paladin.` },
 	{ id: 'sanctified', name: 'Sanctified', maxPoints: 2, row: 5, col: 2, icon: 'ability_paladin_blessedhands.jpg', description: (p) => `Your Seal spells restore ${p * 10}% of your missing mana over their duration and cause your melee attacks to deal ${p * 10}% additional damage.` },
	{ id: 'soldier-of-light', name: 'Soldier of Light', maxPoints: 2, row: 1, col: 3, icon: 'inv_ability_lightsmithpaladin_sacredweapon.jpg', description: (p) => `Gives you a ${p * 15}% chance after parrying or dealing direct Holy damage to reduce the remaining cooldowns of Exorcism and Holy Wrath by ${p * 1} sec.` },
	{ id: 'crusader-strike', name: 'Crusader Strike', maxPoints: 1, row: 4, col: 2, icon: 'spell_holy_crusaderstrike.jpg', details: ['Melee range', '6 sec cooldown'], subDetails: ['5% of base mana', 'Instant'], description: () => `An instant strike that deals 90% weapon damage and refreshes all Judgements on the target.`},
	{ id: 'no-mercy-for-the-wicked', name: 'No Mercy for the Wicked', maxPoints: 5, row: 5, col: 3, icon: 'ability_paladin_sanctifiedwrath.jpg', description: (p) => `Your Avenging Wrath spell no longer causes Forbearance.<br><br>Your Judgement spell and Crusader Strike have a ${p * 5}% chance of causing your next Hammer of Wrath to be usable regardless of the target's health, but you take 50% of the damage inflicted. Lasts 6 sec.`},
            { id: 'righteous-vengeance', name: 'Righteous Vengeance', maxPoints: 3, row: 3, col: 1, prereq: 'conviction', icon: 'ability_paladin_righteousvengeance.jpg', description: (p) => `Your critical strikes with Holy spells and abilities cause your target to burn for additional Holy damage over 10 sec. Stacks up to 5 times.` },
            { id: 'repentance', name: 'Repentance', maxPoints: 1, row: 4, col: 0, icon: 'spell_holy_prayerofhealing.jpg', details: ['20 yd range', '1 min cooldown'], subDetails: ['5% of base mana', 'Instant'], description: () => `Puts the Paladin or their target in a state of meditation, incapacitating them for up to 6 sec. Any damage caused will awaken them. Usable against Demons, Dragonkin, Giants, Humanoids and Undead.
<hr>
If used on self, reduces total threat by 30%.` },
		{ id: 'severance', name: 'Severance', maxPoints: 1, row: 6, col: 1, isUltimate: true, prereq: 'sheath-of-light', icon: 'ability_paladin_lightoftheprotector.jpg', details: ['20 yd range','20 sec cooldown'], subDetails: ['18% of base mana', 'Instant'], description: () => `Unleash an arc of light in front of you, dealing Holy damage equal to 30% of your attack power and reducing the cooldown of Avenging Wrath by 5 sec for each enemy struck.` },
        ]
    }
};
