const CLASS_NAME = "Shaman";
    const talentData = {
    'elemental': {
        name: 'Elemental',
        talents: [
            { id: 'confluence', name: 'Confluence', maxPoints: 5, row: 0, col: 1, icon: 'ability_thunderking_thunderstruck.jpg', description: (p) => `Reduces the mana cost of your Lightning Bolt, Chain Lightning and Shock spells by ${p * 2}%.` },
            { id: 'earth, storm and fire', name: 'Earth, Storm and Fire', maxPoints: 3, row: 0, col: 2, icon: 'spell_nature_elementalprecision_1.jpg', description: (p) => `Reduces the cooldown of your Chain Lightning by ${p * 10}%.<br><br>Increases the periodic damage of your Flame Shock by ${p * 20}%.<br><br>Your Earthbind Totem roots targets for ${p * 1} sec when cast.` },
            { id: 'heat-index', name: 'Heat Index', maxPoints: 5, row: 1, col: 1, icon: 'spell_shaman_spewlava.jpg', description: (p) => `Increases the critical strike damage bonus of your Fire Totems and Fire spells by ${p * 20}%.<br><br>Reduces the delay before your Fire Nova Totem activates by ${p * 1} sec.` },
            { id: 'unstable-totems', name: 'Unstable Totems', maxPoints: 2, row: 0, col: 3, icon: 'shaman_pvp_counterstriketotem.jpg', description: (p) => `Increases the damage of your Fire Totems by ${p * 10}%. Each of your active totems grants you ${p * 1}% spell damage and healing.` },
	{ id: 'elemental-precision', name: 'Elemental Precision', maxPoints: 3, row: 2, col: 2, icon: 'ability_shaman_echooftheelements.jpg', description: (p) => `Increases your chance to hit with Fire, Frost and Nature spells by ${p * 1}% and reduces the threat caused by those spells by ${p * 10}%.` },
            { id: 'elemental-focus', name: 'Elemental Focus', maxPoints: 1, row: 3, col: 1, icon: 'spell_shadow_manaburn.jpg', description: () => `Gives you a 10% chance to enter a Clearcasting state after casting any Fire, Frost, or Nature spell. The Clearcasting state reduces the mana cost of your next 2 spells by 40%.` },
            { id: 'ominous-winds', name: 'Ominous Winds', maxPoints: 2, row: 4, col: 0, icon: 'ability_skyreach_wind.jpg', description: (p) => `Reduces the cooldown of your Shock spells by ${p * 0.5} sec and causes your Wind Shock to lower your threat, making the enemy less likely to attack you.` },
	{ id: 'call-of-thunder', name: 'Call of Thunder', maxPoints: 5, row: 4, col: 1, icon: 'spell_nature_callstorm.jpg', description: (p) => `Increases the critical strike chance of your Nature spells by ${p * 1}%. This effect increases by an additional 2% versus Elementals and Dragonkin.` },
	{ id: 'astral-shift', name: 'Astral Shift', maxPoints: 2, row: 2, col: 3, icon: 'spell_shaman_astralshift.jpg', description: (p) => `When stunned or feared you shift into the Astral Plane, increasing your resistance to dispel mechanics by ${p * 15}% and reducing all damage taken by ${p * 15}% for the duration of the effect.` },
	   { id: 'high-voltage', name: 'High Voltage', maxPoints: 5, row: 1, col: 0, icon: 'spell_shaman_crashlightning.jpg', description: (p) => `Your Lightning Shield orbs cause ${p * 20}% reduced threat and have a ${p * 4}% chance to trigger onto your target when you hit them with Lightning Bolt, Chain Lightning or Stormstrike.` },
            { id: 'eye-of-the-storm', name: 'Eye of the Storm', maxPoints: 2, row: 1, col: 3, icon: 'spell_nature_eyeofthestorm.jpg', description: (p) => `Reduces spell pushback suffered from damaging attacks by ${p * 25}% and reduces the duration of Silence or Interrupt effects used against you by ${p * 5}%. Does not stack with other similar effects.` },
 	{ id: 'elemental-devastation', name: 'Elemental Devastation', maxPoints: 3, row: 1, col: 2, icon: 'classic_spell_fire_elementaldevastation.jpg', description: (p) => `Your spell critical strikes increase your chance to get a critical strike with melee attacks by ${p * 3}% for 10 sec.` },
	{ id: 'lightning-rod', name: 'Lightning Rod', maxPoints: 1, row: 3, col: 0, prereq: 'high-voltage', icon: 'ability_thunderking_lightningwhip.jpg', description: (p) => `Your Lightning Bolt and Chain Lightning spells have a ${p * 50}% chance to add a charge to your active Lightning Shield.` },
      { id: 'storms-reach', name: 'Storm\'s Reach', maxPoints: 2, row: 3, col: 2, icon: 'spell_nature_stormreach.jpg', description: (p) => `Increases the range of your Lightning Bolt and Chain Lightning spells by ${p * 3} yards and reduces their cast time by ${p * 0.5} sec.` },
	 { id: 'electrical-burns', name: 'Electrical Burns', maxPoints: 2, row: 5, col: 2, icon: 'spell_fire_moltenblood.jpg', description: (p) => `Your Chain Lightning can bounce an additional ${p * 1} time(s) and has a ${p * 50}% chance to spread Flame Shock from your primary target to all other enemies struck.` },
	{ id: 'lava-burst', name: 'Lava Burst', maxPoints: 1, row: 2, col: 1, prereq: 'heat-index', icon: 'spell_shaman_lavaburst.jpg', details: ['30 yd range','8 sec cooldown'], subDetails: ['10% of base mana','2 sec cast'], description: () => `Hurl molten lava at the target, dealing Fire damage. If your Flame Shock is on the target, this spell will critically strike.` },
            { id: 'lava-flows', name: 'Lava Flows', maxPoints: 2, row: 4, col: 3, icon: 'spell_shaman_lavaflow.jpg', description: (p) => `Reduces the cast time of your Lava Burst spell by ${p * 0.5} sec. In addition, your Flame Shock periodic damage has a ${p * 5}% chance to reset the cooldown of Lava Burst.` },
	{ id: 'unrelenting-storm', name: 'Unrelenting Storm', maxPoints: 1, row: 4, col: 2, prereq: 'storms-reach', icon: 'spell_nature_unrelentingstorm.jpg', description: (p) => `Regenerate mana equal to ${p * 10}% of your Intellect every 5 sec, even while casting.` },
	{ id: 'lightning-strikes-twice', name: 'Lightning Strikes Twice', maxPoints: 3, row: 5, col: 0, icon: 'spell_nature_lightningoverload.jpg', description: (p) => `Gives your Lightning Bolt and Chain Lightning spells a ${p * 20}% chance to cast a second, similar spell on the same target that costs no mana,  causes no threat, deals half damage and triggers your High Voltage talent.` },
            { id: 'elemental-mastery', name: 'Elemental Mastery', maxPoints: 1, row: 5, col: 1, isUltimate: true, icon: 'spell_nature_wispheal.jpg', details: ['3 min cooldown'], subDetails: ['10% of base mana', 'Instant'], description: () => `Increases your spell critical strike chance and spell haste by 20% for 20 sec.
<hr>
For the duration of this effect your totems are indestructible.` },
	{ id: 'thunderstorm', name: 'Thunderstorm', maxPoints: 1, row: 6, col: 1, isUltimate: true, prereq: 'elemental-mastery', icon: 'spell_shaman_thunderstorm.jpg', details: ['30 sec cooldown'], subDetails: ['Instant'], description: () => `Call down lightning, restoring 20% of your missing mana and damaging nearby enemies within 10 yards. Enemies critically struck by this spell are also knocked back 20 yards. Usable while stunned.` },
        ]
    },
    'enhancement': {
        name: 'Enhancement',
        talents: [
            { id: 'ancestral-knowledge', name: 'Ancestral Knowledge', maxPoints: 5, row: 0, col: 1, icon: 'spell_shadow_grimward.jpg', description: (p) => `Increases your total Agility and Intellect by ${p * 1}%.` },
            { id: 'shield-specialization', name: 'Shield Specialization', maxPoints: 5, row: 2, col: 0, icon: 'inv_shield_17.jpg', description: (p) => `Increases your chance to block attacks with a shield by ${p * 1}% and causes your blocks to restore ${p * 3}% of your missing mana.` },
            { id: 'thundering-strikes', name: 'Thundering Strikes', maxPoints: 5, row: 2, col: 1, icon: 'ability_thunderbolt.jpg', description: (p) => `Improves your chance to get a critical strike with your weapon attacks by ${p * 1}%. This effect increases by an additional 2% versus Elementals and Dragonkin.` },
            { id: 'improved-ghost-wolf', name: 'Improved Ghost Wolf', maxPoints: 2, row: 1, col: 3, icon: 'spell_nature_spiritwolf.jpg', description: (p) => `Your Ghost Wolf spell can be used indoors its cast time is reduced by ${p * 1} sec.` },
            { id: 'primordial-wards', name: 'Primordial Wards', maxPoints: 3, row: 0, col: 2, icon: 'spell_nature_lightningshield.jpg', description: (p) => `Your Lightning, Earth and Water Shield spells gain ${p * 2} additional charges and grant a ${p * 10}% chance of ignoring spell interruption when damaged.` },
            { id: 'enhancing-totems', name: 'Enhancing Totems', maxPoints: 2, row: 0, col: 3, icon: 'spell_nature_earthbindtotem.jpg', description: (p) => `Increases the effects of your Strength of Earth, Grace of Air, Stoneskin and Windwall Totems by ${p * 10}%. Each of your active totems grants you ${p * 1}% Attack Power.` },
            { id: 'imbued-bulwark', name: 'Imbued Bulwark', maxPoints: 3, row: 3, col: 0, icon: 'inv_shield_1h_primalistraid_d_01.jpg', description: (p) => { const values = [25, 50, 100]; return `You can now apply a weapon imbuement to your shield and blocking has a chance to trigger its effect. In addition, the Armor, Block Value, and Stamina provided by your shield is increased by ${values[p - 1]}%.`;}},
	{ id: 'rock-solid', name: 'Rock Solid', maxPoints: 2, row: 5, col: 0, prereq: 'imbued-bulwark', icon: 'item_earthenmight.jpg', description: (p) => `Blocking has a ${p * 25}% chance to add a charge to your active Earth Shield.<br><br>Every 3 charges of Earth Shield reduces your damage taken by ${p * 1}%.` },
            { id: 'primal-strikes', name: 'Primal Strikes', maxPoints: 3, row: 4, col: 1, prereq: 'thundering-strikes', icon: 'artifactability_feraldruid_ashamanesbite.jpg', description: (p) => `Increases your attack speed by ${p * 10}% for your next 3 swings after dealing a critical strike with a spell or ability.` },
            { id: 'weapon-mastery', name: 'Weapon Mastery', maxPoints: 5, row: 2, col: 2, icon: 'ability_hunter_swiftstrike.jpg', description: (p) => `Increases your damage dealt with two-handed weapons by ${p * 1}%.<br><br>Increases your attack speed while dual wielding by ${p * 2}%.` },
	{ id: 'toughness', name: 'Toughness', maxPoints: 5, row: 1, col: 0, icon: 'spell_holy_devotion.jpg', description: (p) => `Increases your armor value from items by ${p * 2}% and increases your Defense skill by ${p * 2}.` },
            { id: 'maelstrom', name: 'Maelstrom', maxPoints: 2, row: 5, col: 1, icon: 'ability_monk_rushingjadewind.jpg', description: (p) => `When you deal damage with a melee weapon, you have a ${p * 5}% chance to gain Maelstrom, stacking up to 5 times. Each stack reduces the cast time of your next Lightning Bolt or Chain Lightning by 20%.` },
            { id: 'earth-and-flame', name: 'Earth and Flame', maxPoints: 2, row: 1, col: 1, icon: 'spell_fire_meteorstorm.jpg', description: (p) => `Rockbiter Weapon increases your threat generation by ${p * 10}%.<br><br>Flametongue Weapon's effect has a ${p * 50}% chance to refresh the duration of your Flame Shock on the target.` },
            { id: 'shamanistic-rage', name: 'Shamanistic Rage', maxPoints: 1, row: 4, col: 2, icon: 'spell_nature_shamanrage.jpg', details: ['15% of base mana', '2 min cooldown'], description: (p) => `Reduces all damage taken by 30% and regenerate mana equal to 80% of your Strength every sec. Usable while stunned. Lasts 15 sec.` },
	{ id: 'ice-and-gale', name: 'Ice and Gale', maxPoints: 2, row: 1, col: 2, icon: 'ability_deathknight_shroudofwinter.jpg', description: (p) => `Frostbrand Weapon's effect increases the damage of Frost Shock by ${p * 10}%. Lasts 30 sec. Stacks up to 3 times.<br><br>Windfury Weapon gains ${p * 10}% increased melee attack power bonus.` },
	{ id: 'shamanistic-fury', name: 'Shamanistic Fury', maxPoints: 3, row: 5, col: 3, prereq: 'shamanistic-rage', icon: 'ability_warrior_endlessrage.jpg', description: (p) => `Shamanistic Rage reduces your total threat by ${p * 10}% and increases your attack speed by ${p * 5}%.` },
	{ id: 'lava-lash', name: 'Lava Lash', maxPoints: 1, row: 6, col: 1, exclusiveGroup: "element-wep", icon: 'ability_shaman_lavalash.jpg', details: ['Melee range','6 sec cooldown'], subDetails: ['8% of base mana', 'Instant','Requires Melee Weapon or Shield'], description: () => `Charge your off-hand weapon or shield with lava, instantly dealing Fire damage equal to 100% off-hand weapon damage or 200% of your shield's block value.<hr>The shaman can no longer learn Cyclone Slash.` },
	{ id: 'cyclone-slash', name: 'Cyclone Slash', maxPoints: 1, row: 6, col: 2, exclusiveGroup: "element-wep", icon: 'ability_skyreach_wind_wall.jpg', details: ['Melee range','12 sec cooldown'], subDetails: ['12% of base mana', 'Instant', 'Requires Two-Handed Weapon'], description: () => `Swing your two-handed weapon in an arc, dealing Physical damage to your primary target and 50% of that damage to all other enemies in a frontal cone.<hr>The shaman can no longer learn Lava Lash.
` },
	{ id: 'thermal-shock', name: 'Thermal Shock', maxPoints: 2, row: 5, col: 2, icon: 'spell_shaman_shockinglava.jpg', description: (p) => `Frost Shock has a ${p * 15}% chance to reset the cooldown of Lava Lash.<br><br>Flame Shock periodic damage has a ${p * 5}% chance to add a charge to your active Lightning Shield.` },
 	{ id: 'static-cling', name: 'Static Cling', maxPoints: 2, row: 3, col: 3, prereq: 'stormstrike', icon: 'shaman_pvp_staticcling.jpg', description: (p) => `Stormstrike has a ${p * 15}% chance to link you with the target. While linked, your attacks with a two-handed weapon always trigger a Lightning Shield orb charge.
<hr>
This effect ends if you move 10 yds away from the target.` },
            { id: 'stormstrike', name: 'Stormstrike', maxPoints: 1, row: 3, col: 2, isUltimate: true, icon: 'spell_shaman_improvedstormstrike.jpg', details: ['Melee range','10 sec cooldown'], subDetails: ['8% of base mana', 'Instant','Requires Melee Weapon'], description: () => `Instantly strike the target, dealing Nature damage equal to weapon damage and restoring 20% of your base mana. Stormstrike has a 25% chance to strike the target an additional time for 40% of normal damage.
<hr>
This effect can chain off of itself.` },
        ]
    },
    'restoration': {
        name: 'Restoration',
        talents: [
            { id: 'improved-healing-waves', name: 'Improved Healing Waves', maxPoints: 5, row: 0, col: 1, icon: 'spell_nature_magicimmunity.jpg', description: (p) => `Reduces the cast time of your Wave spells by ${p * 0.1} sec and reduces the threat caused by those spells by ${p * 3}%.` },
	{ id: 'shamanistic-focus', name: 'Shamanistic Focus', maxPoints: 3, row: 0, col: 2, icon: 'spell_nature_elementalabsorption.jpg', description: (p) => `Your melee hits reduce the mana cost of your next Shock spell by ${p * 5}%. Lasts 6 sec. Stacks up to 5 times.`},
            { id: 'tidal-focus', name: 'Tidal Focus', maxPoints: 5, row: 1, col: 0, icon: 'spell_frost_manarecharge.jpg', description: (p) => `Increases the effectiveness of your healing spells by ${p * 2}% and reduces the mana cost of your totems by ${p * 4}%.` },
	{ id: 'natures-ward', name: 'Nature\'s Ward', maxPoints: 3, row: 1, col: 2, icon: 'flightstone-green.jpg', description: (p) => `When you take damage that brings you below 30% health, your maximum health is increased by ${p * 5}% and you restore ${p * 5}% of your missing mana over 10 sec.
<hr>
This effect can occur once every 45 sec.` },
	{ id: 'tidebringer', name: 'Tidebringer', maxPoints: 2, row: 2, col: 1, icon: 'spell_shaman_blessingofeternals.jpg', description: (p) => `Every 10 sec, the cast time of your next Chain Heal is reduced by ${p * 15}%, and the jump distance increases by ${p * 25}%. Maximum of 2 charges.` },
            { id: 'rapid-reincarnation', name: 'Rapid Reincarnation', maxPoints: 2, row: 1, col: 1, icon: 'spell_nature_reincarnation.jpg', description: (p) => `While you are above 75% health, Reincarnation cools down ${p * 25}% faster. In addition, increases the amount of Health and Mana you reincarnate with by ${p * 10}%.` },
            { id: 'ancestral-guidance', name: 'Ancestral Guidance', maxPoints: 1, row: 2, col: 2, icon: 'ability_shaman_fortifyingwaters.jpg', description: (p) => `Increases your target's armor value by 20% for 10 sec after getting a critical effect from one of your direct healing spells.` },
	{ id: 'guardian-totems', name: 'Guardian Totems', maxPoints: 2, row: 0, col: 3, icon: 'spell_nature_stoneskintotem.jpg', description: (p) => `Reduces the cooldown of your Grounding Totem by ${p} sec. Each of your active totems grants you ${p * 1}% Stamina.` },
            { id: 'tidal-force', name: 'Tidal Force', maxPoints: 1, row: 2, col: 0, prereq: 'tidal-focus', icon: 'ability_mage_waterjet.jpg', description: (p) => `Your Healing Wave and Riptide grant you Tidal Force, which reduces the cast time of your next Healing Rains by 50% or increases the critical effect chance of your next Lesser Healing Wave by 30%. Lasts 6 sec.` },
             { id: 'earthliving-weapon', name: 'Weapon of Life', maxPoints: 5, row: 5, col: 0, icon: 'spell_shaman_earthlivingweapon.jpg', description: (p) => `Your active main-hand Weapon Imbuement now causes your direct healing spells to have a ${p * 4}% chance to grant the target Earthliving, providing healing over 8 sec.` },
            { id: 'blessed-waters', name: 'Blessed Waters', maxPoints: 2, row: 3, col: 1, icon: 'inv_misc_brightwaterlily.jpg', description: (p) => `Increases the healing done by your Healing Stream Totem and Healing Rains by ${p * 15}%. In addition, your critical heals restore ${p * 1}% of your total mana while Water Shield is active.` },
            { id: 'tidal-mastery', name: 'Tidal Mastery', maxPoints: 5, row: 2, col: 3, icon: 'shaman_pvp_ripplingwaters.jpg', description: (p) => `Your Lightning Bolt reduces the mana cost of your healing spells by ${p * 2}%. Stacks up to 5 times. Lasts 20 sec.
<br>
<br>
Your healing spells reduce the cast time of Lightning Bolt by ${p * 3}%. Stacks up to 5 times. Lasts 20 sec.` },
	{ id: 'healing-way', name: 'Healing Way', maxPoints: 3, row: 3, col: 0, icon: 'classic_spell_nature_healingway.jpg', description: (p) => `Your Healing Wave has a ${p * 25}% chance to increase the effect of subsequent Healing Wave spells on that target by 5%. Lasts 15 sec. Stacks up to 3 times.` },
	{ id: 'ancestral-awakening', name: 'Ancestral Awakening', maxPoints: 5, row: 3, col: 2, icon: 'spell_shaman_ancestralawakening.jpg', description: (p) => `Critical heals with Healing Wave or Lesser Healing Wave summon an ancestral spirit to cast a similar spell on a low health party or raid member within 40 yds for ${p * 8}% of the amount healed.` },
            { id: 'ancestral-grace', name: 'Ancestral Grace', maxPoints: 1, row: 4, col: 3, prereq: 'ancestral-awakening', icon: 'inv_ability_farseershaman_ancestralswiftness.jpg', details: ['1 min cooldown'], subDetails: ['10% of base mana'], description: () => `Your next spell deals 20% increased damage or healing and calls forth an ancestral spirit to cast a similar spell.` },
  { id: 'overflowing-life', name: 'Overflowing Life', maxPoints: 3, row: 4, col: 2, icon: 'achievement_zone_wetlands_01.jpg', description: (p) => `Your active Water Totem collects ${p * 5}% of your overhealing done and transfers it to a low health party member within 20 yds every 15 sec.` },
  	{ id: 'riptide', name: 'Riptide', maxPoints: 1, row: 6, col: 1, icon: 'spell_nature_riptide.jpg', details: ['40 yd range','15 sec cooldown'], subDetails: ['3% of base mana', 'Instant'], description: (p) => `Instantly heals a friendly target and provides additional healing over 10 sec. Your Chain Heal ability spreads Riptide's heal over time to all other allies it heals.` },
            { id: 'synergism', name: 'Synergism', maxPoints: 3, row: 5, col: 2, icon: 'achievement_dungeon_throne-of-the-tides.jpg', description: (p) => `You may cast Earth Shield on other friendly targets and it provides ${p * 10}% increased healing.<br><br>Your Wave spells have a ${p * 10}% chance to add a charge to your active Water Shield.` },
	{ id: 'healing-rains', name: 'Healing Rains', maxPoints: 1, row: 4, col: 0, icon: 'ability_evoker_dreamflight.jpg', details: ['40 yd range','15 sec cooldown'], subDetails: ['10% of base mana', '2 sec cast'], description: () => `Create revitalizing rains at a target location, healing up to 5 party or raid members within 15 yds over 10 sec.` },
         { id: 'blessed-tide-totem', name: 'Blessed Tide Totem', maxPoints: 1, row: 5, col: 1, isUltimate: true, prereq: 'blessed-waters', icon: 'ability_shaman_healingtide.jpg', details: ['5 min cooldown'], subDetails: ['3% of base mana','Instant','Tools: Water Totem'], description: () => `Summons a Blessed Tide Totem with 10% of the shaman's health for 12 sec. Party members within 40 yards of the totem gain 200% of the shaman's Spirit and are healed every 2 sec.` },
        ]
}
    };
