const CLASS_NAME = "Warrior";

const talentData = {
        'arms': {
            name: 'Arms',
            talents: [
                { id: 'incite', name: 'Incite', maxPoints: 3, row: 0, col: 0, icon: 'ability_warrior_incite.jpg', description: (p) => `Increases the critical strike chance of your Heroic Strike, Overpower, Thunder Clap and Cleave abilities by ${p * 5}%.` },
                { id: 'improved-rend', name: 'Improved Rend', maxPoints: 3, row: 0, col: 2, icon: 'ability_gouge.jpg', description: (p) => `Increases the damage of your Rend ability by ${p * 10}%. In addition, damage caused by your Rend has a ${p * 5}% chance to generate an additional Rage point.` },
                { id: 'improved-charge', name: 'Improved Charge', maxPoints: 2, row: 0, col: 1, icon: 'ability_warrior_charge.jpg', description: (p) => `Increases the amount of Rage generated by your Charge by ${p * 3} points and reduces its cooldown by ${p * 1} sec.` },
                { id: 'tactical-mastery', name: 'Tactical Mastery', maxPoints: 5, row: 1, col: 1, icon: 'spell_nature_enchantarmor.jpg', description: (p) => `You retain up to ${p * 6} Rage points when you change stances and gain a new effect for each stance.
<hr>
<span class="text-white">Battle:</span> ${p * 1}% increased attack speed.
<br>
<span class="text-white">Berserker:</span> ${p * 1}% increased movement speed.
<br> 
<span class="text-white">Defensive:</span> ${p * 1}% increased parry chance.` },
                { id: 'thunderstruck', name: 'Thunderstruck', maxPoints: 2, row: 1, col: 3, icon: 'warrior_talent_icon_thunderstruck.jpg', description: (p) => `Your Thunder Clap deals additional damage equal to ${p * 5}% of your Attack Power and is usable in any stance.` },
                { id: 'overpowering', name: 'Overpowering', maxPoints: 2, row: 1, col: 0, icon: 'ability_meleedamage.jpg', description: (p) => `Your Overpower ability has a ${p * 10}% chance to activate whenever you deal damage with Rend.
<hr>
This effect can occur once every 10 sec.` },
                { id: 'anger-management', name: 'Anger Management', maxPoints: 1, row: 2, col: 1, prereq: 'tactical-mastery', icon: 'spell_holy_blessingofstamina.jpg', description: () => `Generate 1 Rage per 3 seconds while in combat and your Rage decays at a 30% slower rate while out of combat.` },
                { id: 'deep-wounds', name: 'Deep Wounds', maxPoints: 3, row: 1, col: 2, icon: 'ability_backstab.jpg', description: (p) => `Your critical strikes cause the opponent to bleed, dealing ${p * 20}% of your melee weapon's average damage over 12 sec.` },
                { id: 'second-wind', name: 'Second Wind', maxPoints: 2, row: 4, col: 2, icon: 'ability_hunter_harass.jpg', description: (p) => `Whenever you are struck by a Stun, Immobilize or Knock Back effect you generate ${p * 5} Rage points and ${p * 5}% of your missing health over 5 sec.` },
                { id: 'brutalize', name: 'Brutalize', maxPoints: 1, row: 4, col: 3, icon: 'ability_warrior_trauma.jpg', details: ['Melee Range', '20 sec cooldown'], subDetails: ['30 Rage','Instant cast'], description: () => `Brutalize your target, dealing 80% weapon damage and causing your Bleed effects on them to spread to enemies within 10 yds.` },
                { id: 'master-of-arms', name: 'Master of Arms', maxPoints: 1, row: 4, col: 1, prereq: 'two-handed-weapon-specialization', icon: 'garrison_building_armory.jpg', description: (p) => `Your equipped weapon has a 5% chance to:
<br>
<br>
Axe / Polearm -  Critically strike.
<br>
Mace / Fist Weapon -  Stun the target for 3 sec.
<br>
Sword / Staff / Glaive -  Gain an extra attack.
<hr>
Switching weapons during combat places this effect on a 10 sec cooldown.` },
     { id: 'blood-frenzy', name: 'Blood Frenzy', maxPoints: 2, row: 3, col: 2, icon: 'ability_warrior_bloodfrenzy.jpg', description: (p) => `Increases your melee attack speed by ${p * 5}%.<br><br>Applying a bleed effect to an enemy also increases all physical damage they take by ${p * 2}% for 1 min.` },
                { id: 'two-handed-weapon-specialization', name: 'Two-Handed Weapon Specialization', maxPoints: 5, row: 3, col: 1, icon: 'inv_axe_09.jpg', description: (p) => `Increases your damage and chance to hit with two-handed melee weapons by ${p}%.` },
	{ id: 'strength-of-arms', name: 'Strength of Arms', maxPoints: 5, row: 3, col: 0, icon: 'inv_1115_warrior_victorypose.jpg', description: (p) => `Increases your total Strength and Stamina by ${p * 1}% and reduces the cooldown of your Retaliation, Recklessness and Shield Wall abilities by ${p * 4} mins. ` },
                { id: 'impale', name: 'Impale', maxPoints: 2, row: 2, col: 2, prereq: 'deep-wounds', icon: 'ability_searingarrow.jpg', description: (p) => `Increases the critical strike damage bonus of your abilities by ${p * 5}%.` },
                { id: 'sweeping-strikes', name: 'Sweeping Strikes', maxPoints: 1, row: 5, col: 1, icon: 'ability_rogue_slicedice.jpg', details: ['30 sec cooldown'], subDetails: ['15 Rage','Instant cast'], description: () => `Your next 5 melee attacks strike an additional nearby opponent.` },
                { id: 'crimson-cyclone', name: 'Crimson Cyclone', maxPoints: 2, row: 4, col: 0, icon: 'ability_ironmaidens_swirlingvortex.jpg', description: (p) => `Your Whirlwind hits reduce the cooldown of your Brutalize ability and your Overpowering talent by ${p * 1} sec.` },
                { id: 'attrition', name: 'Attrition', maxPoints: 2, row: 5, col: 2, icon: 'achievement_bg_winwsg_3-0.jpg', description: (p) => { const cooldownValues = [10, 5]; return `The cost of Hamstring and Meathook decreases by 1 Rage point every ${cooldownValues[p - 1]} sec in combat. In addition, when you Slam a Dazed target you have a ${p * 5}% chance to knock them down.`;}},
                { id: 'meathook', name: 'Meathook', maxPoints: 1, row: 2, col: 0, icon: 'inv_fishing_bait_spinefinpiranha.jpg', details: ['30 yd range','35 sec cooldown'], subDetails: ['5 Rage','Instant cast'], description: (p) => `Throw out a hooked chain to pull the target toward you and immobilize them for 3 sec.
<hr> 
Ineffective on enemies higher than level 61 or which are marked as boss enemies.` },
                { id: 'juggernaut', name: 'Juggernaut', maxPoints: 1, row: 5, col: 0, icon: 'warrior_talent_icon_skirmisher.jpg', description: (p) => `Intervene removes all movement impairing effects.<br><br>Charge refreshes the duration of Second Wind.<br><br>Intercept increases the damage of your next Slam by ${p * 10}%. Lasts 8 sec.` },
                { id: 'mortal-strike', name: 'Mortal Strike', maxPoints: 1, row: 6, col: 1, prereq: 'sweeping-strikes', isUltimate: true, icon: 'ability_warrior_savageblow.jpg', details: ['Melee Range', '6 sec cooldown'], subDetails: ['25 Rage','Instant cast'], description: () => `A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec.` },
            ]
        },
        'fury': {
            name: 'Fury',
            talents: [
                { id: 'booming-voice', name: 'Booming Voice', maxPoints: 5, row: 0, col: 1, icon: 'ability_warrior_commandingshout.jpg', description: (p) => `Reduces the Rage cost of your Shout abilities by ${p * 1}. In addition, increases the area of effect and duration of your Battle Shout and Demoralizing Shout by ${p * 10}%.` },
                { id: 'monster-slaying', name: 'Monster Slaying', maxPoints: 5, row: 0, col: 2, icon: 'ability_dragonriding_dragonridersinitiative01.jpg', description: (p) => `Increases your chance to get a critical strike with all weapons by ${p}%. This effect increases by an additional 2% versus Dragonkin and Giants.` },
                { id: 'flagellation', name: 'Flagellation', maxPoints: 2, row: 1, col: 1, icon: 'ability_warrior_intensifyrage.jpg', description: (p) => `You generate ${p * 15}% additional Rage from direct damage taken.` },
                { id: 'break-through', name: 'Break Through', maxPoints: 3, row: 1, col: 0, icon: 'inv_1115_warrior_fastermeleeattacks.jpg', description: (p) => `Reduces the chance for your attacks to be dodged or parried by ${p}%.` },
                { id: 'unbridled-wrath', name: 'Unbridled Wrath', maxPoints: 5, row: 1, col: 2, icon: 'ability_warrior_focusedrage.jpg', description: (p) => `Being Enraged increases your total Strength by ${p * 1}% and your Rage generation from damage dealt by ${p * 4}%.` },
                { id: 'dismember', name: 'Dismember', maxPoints: 1, row: 2, col: 0, prereq: 'break-through', icon: 'warrior_talent_icon_ravager.jpg', description: (p) => `Your Cleave ability hits ${p} additional target and deals 25% increased damage.` },
                { id: 'piercing-howl', name: 'Piercing Howl', maxPoints: 1, row: 2, col: 1, icon: 'spell_shadow_deathscream.jpg', subDetails: ['10 Rage','Instant cast'], description: () => `Causes all enemies near the warrior to be Dazed, reducing movement speed by 50% for 6 sec.` },
                { id: 'blood-craze', name: 'Blood Craze', maxPoints: 3, row: 2, col: 2, icon: 'spell_shadow_summonimp.jpg', description: (p) => `Regenerates ${p * 2}% of your total Health over 6 sec after being the victim of a critical strike or damage that exceeds 15% of your total Health.` },
                { id: 'voracity', name: 'Voracity', maxPoints: 1, row: 2, col: 3, prereq: 'blood-craze', icon: 'ability_racial_pureblood.jpg', description: (p) => `Blood Craze now counts as an Enrage effect and activates whenever you Execute a target that yields experience or honor.` },
                { id: 'dual-wield-specialization', name: 'Dual Wield Specialization', maxPoints: 5, row: 4, col: 1, prereq: null, icon: 'ability_dualwield.jpg', description: (p) => `Increases the damage done by your offhand weapon by ${p * 5}%.` },
                { id: 'sudden-death', name: 'Sudden Death', maxPoints: 2, row: 3, col: 1, icon: 'ability_warrior_improveddisciplines.jpg', description: (p) => `Your melee hits on bleeding targets have a ${p * 5}% chance to allow one use of Execute regardless of the target's health, but it only consumes a maximum of 20 rage.` },
                { id: 'foment', name: 'Foment', maxPoints: 5, row: 3, col: 2, icon: 'ability_ironmaidens_maraksbloodcalling.jpg', description: (p) => `Dealing a melee critical strike grants you Foment, increasing your attack speed by ${p * 3}%. Lasts 10 sec.
<br>
<br>
Being the victim of a critical strike grants you Seethe, increasing your damage dealt by ${p * 2}%. Lasts 10 sec.<hr>Foment and Seethe both count as Enrage effects.` },
                { id: 'improved-slam', name: 'Improved Slam', maxPoints: 2, row: 3, col: 0, icon: 'ability_warrior_decisivestrike.jpg', description: (p) => {const castTimeValues = [50, 100]; return `Reduces the cast time of your Slam by ${castTimeValues[p - 1]}%. In addition, your Bloodthirst and Mortal Strike abilities have a ${p * 15}% chance to make your next Slam cost no Rage.`;}},
	{ id: 'single-minded-fury', name: 'Single-Minded Fury', maxPoints: 2, row: 4, col: 0, prereq: 'improved-slam', icon: 'warrior_talent_icon_singlemindedfury.jpg', description: (p) => `Your Slam ability deals ${p * 10}% increased damage and hits with both weapons while dual wielding.` },
                { id: 'deathwish', name: 'Deathwish', maxPoints: 1, row: 5, col: 1, icon: 'spell_shadow_deathpact.jpg', details: ['3 min cooldown'], subDetails: ['Instant'], description: () => `When activated, increases your physical damage by 20% and makes you immune to Fear and Daze effects, but lowers your armor and all resistances by 50%. Lasts 30 sec.` },
	{ id: 'to-the-death', name: 'To The Death', maxPoints: 1, row: 4, col: 3, prereq: 'foment', icon: 'spell_warrior_barbarian.jpg', description: (p) => `The next time you take fatal damage you return to full health that decays over 10 sec. During this time you cannot be granted heals, shields or immunity effects.<hr>This effect can occur once every 30 min.` },
                { id: 'seething-fury', name: 'Seething Fury', maxPoints: 3, row: 5, col: 0, icon: 'warrior_talent_icon_furyintheblood.jpg', description: (p) => `While Berserker Rage is active, the first attack made against you deals ${p * 10}% less damage, and subsequent attacks against you increases the damage of your Bloodthirst ability by ${p * 1}%. Stacks up to 5 times.` },
                { id: 'pillagers-call', name: 'Pillager\'s Call', maxPoints: 1, row: 5, col: 2, prereq: 'foment', icon: 'achievement_bg_kill_flag_carriereos.jpg', details: ['5 min cooldown'], subDetails: ['100 Rage','Instant','Reagents: Any Cloth'], description: (p) => `Place a banner that causes you and any party members within 20 yds to become Enraged, gaining increased size and critical strike chance with melee and ranged weapons. Lasts 20 sec.
<hr>
Your Intercept ability has no cooldown while standing within your banner's radius.` },
                { id: 'warpath', name: 'Warpath', maxPoints: 2, row: 5, col: 3, icon: 'spell_warrior_dragoncharge.jpg', description: (p) => `Your Charge and Intercept abilities damage all enemies standing between you and your target for an amount equal to ${p * 15}% of your Attack Power.` },
                { id: 'bloodthirst', name: 'Bloodthirst', maxPoints: 1, row: 6, col: 1, isUltimate: true, prereq: 'deathwish', icon: 'spell_nature_bloodlust.jpg', details: ['Melee Range', '6 sec cooldown'], subDetails: ['30 Rage','Instant cast'], description: () => `An instant attack that causes damage equal to 45% of your Attack Power. In addition, your next 3 melee attacks restore 2% of missing health, increased by 1% for every active enrage effect on you. Lasts 8 sec.` },
            ]
        },
        'protection': {
            name: 'Protection',
            talents: [
                { id: 'shield-specialization', name: 'Shield Specialization', maxPoints: 5, row: 0, col: 1, icon: 'inv_shield_06.jpg', description: (p) => `Increases your chance to block attacks with a shield by ${p}% and has a ${p * 20}% chance to generate 1 Rage when a block occurs.` },
                { id: 'improved-bloodrage', name: 'Improved Bloodrage', maxPoints: 2, row: 2, col: 2, icon: 'ability_racial_bloodrage.jpg', description: (p) => `Increases the Rage generated by your Bloodrage ability by ${p * 25}%. In addition, the cooldown of Bloodrage is reduced by ${p * 1} sec whenever you parry.` },
                { id: 'toughness', name: 'Toughness', maxPoints: 5, row: 1, col: 2, icon: 'spell_holy_devotionaura.jpg', description: (p) => `Increases your armor value from items by ${p * 2}% and your Defense skill by ${p * 2}.` },
                { id: 'iron-will', name: 'Iron Will', maxPoints: 5, row: 0, col: 2, icon: 'spell_magic_magearmor.jpg', description: (p) => `Reduces the duration of Stun and Charm effects on you by ${p * 5}%. In addition, reduces the amount of durability lost whenever you block or take damage by ${p * 10}%.` },
                { id: 'last-stand', name: 'Last Stand', maxPoints: 1, row: 3, col: 0, prereq: 'devastating-defense', icon: 'spell_holy_ashestoashes.jpg', details: ['5 min cooldown'], subDetails: ['Instant'], description: () => `Temporarily grants you 30% of your maximum Health for 20 sec. After the effect expires, the health is lost.` },
                { id: 'improved-shield-block', name: 'Improved Shield Block', maxPoints: 1, row: 2, col: 1, prereq: 'shield-specialization', icon: 'ability_defend.jpg', description: (p) => `Allows your Shield Block ability to block an additional attack and increases the duration by 1 sec.` },
                { id: 'wrathful-protector', name: 'Wrathful Protector', maxPoints: 2, row: 3, col: 3, icon: 'ability_fixated_state_red.jpg', description: (p) => `Revenge increases your attack speed by ${p * 15}% for 3 sec and has a ${p * 5}% chance to activate whenever a nearby party member takes damage.` },
                { id: 'defiance', name: 'Defiance', maxPoints: 3, row: 2, col: 3, icon: 'ability_warrior_innerrage.jpg', description: (p) => `Increases your threat generation by ${p * 5}% and your chance to hit with weapon attacks by ${p}%.` },
                { id: 'devastating-defense', name: 'Devastating Defense', maxPoints: 3, row: 1, col: 0, icon: 'achievement_garrisonfollower_epic.jpg', description: (p) => `Reduces the cost of your offensive abilities by ${p} Rage point(s) and causes Sunder Armor to deal damage equal to ${p * 50}% of your equipped shield's block value.` },
                { id: 'deft-combatant', name: 'Deft Combatant', maxPoints: 2, row: 3, col: 1, icon: 'ability_warrior_disarm.jpg', description: (p) => `The duration of Disarm effects on you is reduced by ${p * 25}% and you deal ${p * 5}% increased damage to Disarmed, Stunned and Dazed enemies.` },
                { id: 'vigilance', name: 'Vigilance', maxPoints: 2, row: 3, col: 2, icon: 'spell_nature_reincarnation.jpg', description: (p) => `When a party or raid member falls below 40% total Health, the cooldown of your Taunt is reset and you Enrage, gaining ${p * 10}% increased damage for 10 sec.
<hr>
This effect can occur once every 45 sec.` },
                { id: 'rolling-thunder', name: 'Rolling Thunder', maxPoints: 2, row: 1, col: 3, icon: 'inv_sonic_wave.jpg', description: (p) => `Cleave deals ${p * 25}% increased damage to enemies affected by Thunder Clap and refunds ${p * 1} Rage point(s) per target struck.` },
                { id: 'concussion-blow', name: 'Concussion Blow', maxPoints: 1, row: 4, col: 1, icon: 'ability_thunderbolt.jpg',details: ['Melee Range', '45 sec cooldown'], subDetails: ['15 Rage','Instant'], description: () => `Stuns the opponent for 5 sec.` },
                { id: 'spell-breaker', name: 'Spellbreaker', maxPoints: 1, row: 6, col: 2, prereq: 'shield-slam',  icon: 'ability_warrior_shieldbreak.jpg', description: (p) => `Your Shield Bash ability is no longer on the Global Cooldown and deals damage equal to your Shield Slam on targets that are innately immune to interrupts.` },
	{ id: 'heavy-repercussions', name: 'Heavy Repercussions', maxPoints: 2, row: 5, col: 2, icon: 'ability_warrior_shieldcharge.jpg', description: (p) => `While Shield Block is active your Shield Slam hits deal ${p * 10}% increased damage and reduce the cooldown of your Intervene ability by  ${p} sec.` },
                { id: 'improved-spell-reflection', name: 'Improved Spell Reflection', maxPoints: 2, row: 4, col: 0, icon: 'ability_pvp_softenedblows.jpg', description: (p) => `Reduces the cost of your Spell Reflection ability by ${p * 10} Rage points. Reflecting a spell reduces all spell damage taken from that school of magic by ${p * 5}% for 8 sec.` },
                { id: 'iron-man', name: 'Iron Man', maxPoints: 3, row: 5, col: 0, icon: 'ability_pvp_hardiness.jpg', description: (p) => `Increases your total Stamina by ${p * 1}% and causes you to gain attack power equal to ${p * 1}% of your current Health.` },
                { id: 'valiance', name: 'Valiance', maxPoints: 5, row: 4, col: 2, icon: 'spell_warrior_sharpenblade.jpg', description: (p) => `Increases your critical strike chance with One-Handed Melee weapons by ${p * 1}%. This effect is doubled versus enemies that aren't targeting you.` },
                { id: 'sword-and-board', name: 'Sword and Board', maxPoints: 1, row: 5, col: 3, prereq: 'valiance', icon: 'ability_warrior_swordandboard.jpg', description: (p) => `Sunder Armor and Revenge have a ${p * 30}% chance of refreshing the cooldown of your Shield Slam and reducing its Rage cost by 100% for 6 sec.` },
                { id: 'shield-slam', name: 'Shield Slam', maxPoints: 1, row: 6, col: 1, isUltimate: true, prereq: 'concussion-blow', icon: 'inv_shield_05.jpg', details: ['Melee Range', '6 sec cooldown'], subDetails: ['20 Rage','Instant cast'], description: () => `Slams the target with your shield, causing damage modified by your block value, and has a 50% chance of dispelling 1 magic effect on the target. Causes a high amount of threat.` }
            ]
        }
    };
